M48
; DRILL file {KiCad 9.0.7} date 2026-09-07T13:16:34+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-07T13:16:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X92.11Y-57.4
X97.89Y-57.4
T2
X54.0Y-54.0
X54.0Y-126.0
X146.0Y-54.0
X146.0Y-126.0
M30
